- name: Add workers IPs to /etc/hosts
  lineinfile:
    path: /etc/hosts
    regexp: "^.*{{ item }}$"
    line: "{{ hostvars[item]['ansible_host'] }}    {{ item }}"
  with_items: "{{ groups['k8s-workers'] }}"

- name: Copy binaries
  copy:
    src: "{{ item }}"
    dest: /usr/local/bin/
    owner: root
    group: k8s
    mode: 0555
  loop:
    - '{{ BIN_DIR }}/kube-apiserver'
    - '{{ BIN_DIR }}/kube-controller-manager'
    - '{{ BIN_DIR }}/kube-scheduler'
    - '{{ BIN_DIR }}/kubectl'

- name: Create config directories
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: k8s
    mode: 0755
  loop:
    - /var/lib/kubernetes
    - /etc/kubernetes/config

- name: Copy kubeconfigs to master nodes
  copy:
    src: "{{ CONF_DIR }}/{{item}}"
    dest: "/var/lib/kubernetes/"
    owner: root
    group: k8s
    mode: 0640
  with_items:
    ['kube-controller-manager.kubeconfig', 'kube-scheduler.kubeconfig']

- name: Copy certificates and keys
  copy:
    src: "{{ item }}"
    dest: /var/lib/kubernetes/
    owner: root
    group: k8s
    mode: 0640
  loop:
    - '{{ PKI_DIR }}/ca.pem'
    - '{{ PKI_DIR }}/ca-key.pem'
    - '{{ PKI_DIR }}/k8s-master.pem'
    - '{{ PKI_DIR }}/k8s-master-key.pem'
    - '{{ PKI_DIR }}/encryption-config.yml'
    - '{{ PKI_DIR }}/service-account.pem'
    - '{{ PKI_DIR }}/service-account-key.pem'

- name: kube-scheduler.yaml
  copy:
    src: etc/kubernetes/config/kube-scheduler.yaml
    dest: /etc/kubernetes/config
    owner: root
    group: k8s
    mode: 0640

- name: Copy systemd unit file
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: k8s
    mode: 0644
  with_items: 
    - { src: "lib/systemd/system/kube-apiserver.service.j2"          , dest: "/lib/systemd/system/kube-apiserver.service" }
    - { src: "lib/systemd/system/kube-controller-manager.service.j2" , dest: "/lib/systemd/system/kube-controller-manager.service" }
    - { src: "lib/systemd/system/kube-scheduler.service.j2"          , dest: "/lib/systemd/system/kube-scheduler.service" }
  notify:
    - restart k8s-master
  tags:
    - config

- meta: flush_handlers

